config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'main/show'
  get 'main/login'
  get 'main/logout'
  get 'main/privacy'

  namespace :rp do
    get 'twitter/index'
    get 'twitter/create'
    get 'twitter/show'
    get 'facebook/index'
    get 'facebook/create'
    get 'facebook/show'
    get 'google/index'
    get 'google/create'
    get 'google/show'
  end

  root to: 'main#index'
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# Auths-demo app Main controller
class MainController < ApplicationController
  skip_before_action :authenticate, only: %i[index login privacy]

  def index
    @logined = authenticated?
  end

  def show
    redirect_to @token_set['redirect']
  end

  def login; end

  def logout
    session.delete(:access_token_set)
    redirect_to main_index_path
  end

  def privacy; end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<main>
<h1>Auths Demo Main View</h1>

<% if @logined %>
  <h3>あなたは <%= @token_set['provider'] %> でログインしています</h3>
  <p>操作を選択してください</p>
  <p><%= link_to 'プロファイル情報を表示する', main_show_path %></p>
  <p><%= link_to 'ログアウトする', main_logout_path %></p>
  <p><%= link_to 'Privacy Policy', main_privacy_path %></p>
<% else %>
  <h3>ログインされていません</h3>
  <p>以下のリンクよりサイトにログインしてください</p>
  <p><%= link_to 'ログインする', main_login_path %></p>
  <p><%= link_to 'Privacy Policy', main_privacy_path %></p>
<% end %>
</main>

app/views/main/login.html.erb
<main data-turbolinks="false">
<h1>ユーザ登録／ログイン</h1>

<!--
 ##############################################################
  リンク先で外部サイトにリダイレクトするような場合は、
  data-turbolinks を false にしないとリンクが２重発火してしまう
 ###############################################################
-->
  <p>
  ご指定の操作にはユーザ登録／ログインが必要です
  <br>
  お持ちのアカウントでユーザ登録／ログインをお願いします
  </p>
  <p>
  <%= link_to rp_twitter_index_path do %>
    Twitter でログイン
  <% end %>
  </p>
  <p>
  <%= link_to rp_facebook_index_path do %>
    Facebook でログイン
  <% end %>
  </p>
  <p>
  <%= link_to rp_google_index_path do %>
    Google でログイン
  <% end %>
  </p>
  <p>
  <%= link_to main_index_path do %>
    Main View に戻る
  <% end %>
  </p>
</main>

app/views/main/logout.html.erb
<h1>Main#logout</h1>
<p>Find me in app/views/main/logout.html.erb</p>

app/views/main/privacy.html.erb
<main>
<h1>プライバシーポリシー</h1>
「https://webgame.link/auths/」（以下、当サイト）は、利用者の個人情報をお預かりするにあたり、以下のとおり個人情報保護方針を定め、個人情報を保護いたします。

<h3>個人情報の収集について</h3>
<p>
本サイトにログインする際に、利用者の氏名やメールアドレス、プロフィール画像等の個人情報を収集いたします。収集した個人情報は、サーバ内のメモリおよびセッション情報にのみ一時的に保持いたしますが、ファイルやデータベースに保存することはありません。収集した個人情報はサーバ内で秘密管理され、第三者に開示・共有することは一切ありません。
</p>

<h3>ウェブサーバの記録</h3>
<p>
当サイトのウェブサーバは、利用者のコンピュータのIPアドレスを自動的に収集・記録しますが、これらは利用者個人を特定するものではありません。
</p>

<h3>免責事項</h3>
<p>
当サイトからリンクされた当サイト以外のウェブサイトの内容やサービスに関しては、当サイトの個人情報保護についての諸条件は適用されません。当サイト以外のウェブサイトの内容および個人情報の保護に関しても、当サイト管理者は責任を負いません。
</p>
<p>
<%= link_to main_index_path do %>
  Main View に戻る
<% end %>
</p>
</main>

app/views/main/show.html.erb
<h1>Main#show</h1>
<p>Find me in app/views/main/show.html.erb</p>